# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20180111_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='req_type',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='u_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='u_email',
            field=models.EmailField(max_length=254),
        ),
    ]
