# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 10:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default=datetime.datetime(2018, 1, 23, 10, 24, 2, 793981, tzinfo=utc), max_length=50),
        ),
    ]
