# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 14:22
from __future__ import unicode_literals

import calc.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20180123_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charimage', models.ImageField(upload_to=calc.models.charimage_upload_path, verbose_name='Uploaded Image')),
                ('title', models.CharField(default=datetime.datetime(2018, 5, 7, 14, 22, 1, 420820, tzinfo=utc), max_length=50)),
                ('req_type', models.CharField(max_length=1)),
                ('sub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=calc.models.image_upload_path, verbose_name='Uploaded Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default=datetime.datetime(2018, 5, 7, 14, 22, 1, 407540, tzinfo=utc), max_length=50),
        ),
    ]
