# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20180507_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charimage',
            old_name='charimage',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='charimage',
            name='title',
            field=models.CharField(default=datetime.datetime(2018, 5, 7, 14, 39, 39, 89597, tzinfo=utc), max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default=datetime.datetime(2018, 5, 7, 14, 39, 39, 76734, tzinfo=utc), max_length=50),
        ),
    ]
