# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20180507_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charimage',
            name='title',
            field=models.CharField(default=datetime.datetime(2018, 5, 7, 15, 13, 11, 834274, tzinfo=utc), max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default=datetime.datetime(2018, 5, 7, 15, 13, 11, 816067, tzinfo=utc), max_length=50),
        ),
    ]
